### ISSUE TITLE
GPL license contradiction

### ISSUE THREAD

**Issue by HerrHulaHoop** [Inori/GPCS4#1]
Hi! Nice to see yet another PS4 emulator in the works. Just noticed a problem with license though. You've opted for GPLv3 license but have also mentioned 
> But commercial usage is NOT permitted.

The GPLv3 specifically prohibits adding further restrictions over and above what the license originally states. 

See section 10:
> You may not impose any further restrictions on the exercise of the rights granted or affirmed under this License.

Also section 7 further stipulates 6 conditions that you _may_ add over and above the license, non-commercial usage not being one of them. So in which case this applies:
> If the Program as you received it, or any part of it, contains a notice stating that it is governed by this License along with a term that is a further restriction, you may remove that term.

So people can simply ignore the condition preventing commercial usage and they will still not be in violation of the license. I'd suggest you avoid using a GPL license if you wish to restrict people from using your program commercially.

**Comment by Inori** [comment]
Thanks for your notification. I'm not very familiar with license things.
You're right. I'll change the license or make one myself.

**Comment by videah** [comment]
> 
> 
> Thanks for your notification. I'm not very familiar with license things.
> You're right. I'll change the license or make one myself.

Please don't write a license without consulting a lawyer, it leads to all sorts of nasty problems down the line.

**Comment by Inori** [comment]
Deleted.
