### ISSUE TITLE
Pkg/PFS support

### ISSUE THREAD

**Issue by Fox2Code** [Inori/GPCS4#101]
`.pkg` files are special, they contain an encrypted (but decryptable, see documentation) PFS file-system.

The PFS filesystem should contain `eboot.bin` at the root of it.

Unofficial documentation:
https://psdevwiki.com/ps4/Package_Files
https://psdevwiki.com/ps4/PFS

For full PSF implementation some additional steps are needed like getting the title id from an xml file. (Not inside PFS)

`<titlepatch titleid="CUSAXXXXX">` <- this is header, but `CUSA00001` seems to be a good fallback if unable to read xml.

`/mnt/sandbox/pfsmnt/CUSAXXXXX-app0/` <- PFS should be "mounted" there.

For raw `eboot.bin` usage, just linking it to `/mnt/sandbox/pfsmnt/CUSA00001-app0/eboot.bin` should be good enough.

Note: The issue is only about running basic homebrews that don't encrypt their assets, not about running full games.

**Comment by Inori** [comment]
Thanks, PKG support is definitely needed, but not now.
BTW, ff there's some usable code for this format, that will be more good. :)

**Comment by Masamune3210** [comment]
To start, you could probably take a look at how to parse them by looking into open source library managers like https://github.com/pearlxcore/PS4-PKG-Tool

**Comment by Inori** [comment]
> To start, you could probably take a look at how to parse them by looking into open source library managers like https://github.com/pearlxcore/PS4-PKG-Tool

That's good👍
