### ISSUE TITLE
Sharing some code with orbital

### ISSUE THREAD

**Issue by LifeIsStrange** [Inori/GPCS4#103]
Orbital roadmap mentions they have a
GCN-to-SPIRV translator.
Cf https://github.com/AlexAltea/orbital/wiki/Roadmap
Since this is hard to get right, maybe you could join forces/code on this specific task?

**Comment by Inori** [comment]
well, thanks for your advice, I've known Orbital for a long time.
And I also remember they actually had a GCN recompiler in their repository, but now it seems been removed.

**Comment by LifeIsStrange** [comment]
BTW good luck, we all have a lot of admiration for your ambitious goal :)
