### ISSUE TITLE
Technical estimation of difficulty to emulate PS4 vs newer consoles

### ISSUE THREAD

**Issue by LifeIsStrange** [Inori/GPCS4#104]
I am not an expert but like many i would have expected the PS4 to be easier to emulate than the PS3 since its hardware is much closer to PC.
As for the CPU you can just use the host x86 cpu through a hypervisor e.g haxm which is what orbital is doing. Or by using e.g. Box64

The remaining complexities would be:
Low level differences vs a regular pc architecture
And notably, a GPU API mismatch (the PS4 expect raw GCN assembly??)
However I think it would be a mistake to not seriously ask yourself whether the PS5 would be actually easier to emulate.
It's still x86 and an updated GCN but it might have less lower level differences vs a regular pc architecture and might have less of a GPU api mismatch.

But my neophyte opinion would be that the Xbox series X/S would be the easiest platform to emulate.
Since it's still a x86, updated GCN BUT If I recall correctly, xbox serie X games are coded in direct X 12, which is much easier to map to vulkan and crucially is natively supported on windows. The OSes would also match.

Unrelated, if the GCN to spirv mapping is a ley difficulty, couldn't you offload GCN assembly directly to the host GPU if the host GPU is an AMD gpu?
The switch emulator Yuzu supports this for Nvidia gpus.

BTW I really think you should do a patreon, even if it's just currently a part time project, it could become big!

**Comment by Masamune3210** [comment]
There are quite a few major differences between Desktop Windows and GameOS which is what runs while playing a game on the One/Series consoles. 

We really don't know enough about the ps5 to know how close to a PC it is or not. The ps4 was thought to be really close to a PC at first as well but porting Linux to it showed just how wrong that statement can be

**Comment by Fox2Code** [comment]
For now the project look like it took a bit the Wine path, where it's neither a emulator or container but a translation layer.

This means PS4 games are in the same memory space than system libraries.

On one side it reduce the overhead and latency of emulation or virtualization, but it also make compatibility more limited.

**Comment by Inori** [comment]
> PS5 would be actually easier to emulate

Not sure for PS5, haven't dig in too much for that, just guess it's pretty similar to PS4, and if this is true,  these's not much difference about the things to do.

> The switch emulator Yuzu supports this for Nvidia gpus.

I thought it is even impossible before you tell me that Yuzu support it, maybe we can have a try in the future.

**Comment by LifeIsStrange** [comment]
about yuzu support for assembly its
https://en.wikipedia.org/wiki/ARB_assembly_language
As for reusing AMD GCN assembly I have no idea, maybe https://github.com/SunsetQuest/Asm4GCN it seems like a topic nobody knows much about :m

**Comment by VelocityRa** [comment]
> Unrelated, if the GCN to spirv mapping is a ley difficulty, couldn't you offload GCN assembly directly to the host GPU if the host GPU is an AMD gpu?
The switch emulator Yuzu supports this for Nvidia gpus.

Source? I really doubt that's the case.
Maybe you're confusing its GLASM backend with this? Because in that case it's not "direct" at all as far as I can tell, it still has to be translated.

**Comment by Masamune3210** [comment]
Yeah, that's GLASM, and no, it's basically assembly but for the GPU and only works on Nvidia's GPU because AMD doesn't know how to follow a standard to save their life

**Comment by Inori** [comment]
So this is not a really issue, I shall close it.
