### ISSUE TITLE
Use spdlog for logging & fmt for string formatting

### ISSUE THREAD

**Issue by VelocityRa** [Inori/GPCS4#11]
For logging: https://github.com/gabime/spdlog
For general formatting: https://github.com/fmtlib/fmt

Also, spdlog uses fmt's syntax (it's bundled).

**Comment by Inori** [comment]
Yes, I've followed your advice, and the work is done, see https://github.com/Inori/GPCS4/tree/logger_altering
Just haven't merged into master
