### ISSUE TITLE
Unresolved externals?

### ISSUE THREAD

**Issue by thx4ever** [Inori/GPCS4#114]
Hi, i tried to compile this emulator with clang12, visual studio 2019 and at the end stage have errors

 Creating library C:\Users\thx4ever\Desktop\GPCS4\x64\Release\GPCS4.lib and object C:\Users\thx4ever\Desktop\GPCS4\x64\Release\GPCS4.exp
2>SceGnmDriver.obj : : error LNK2019: unresolved external symbol "public: __cdecl sce::vlt::VltInstance::VltInstance(void)" (??0VltInstance@vlt@sce@@QEAA@XZ) referenced in function "private: bool __cdecl sce::SceGnmDriver::createVltDevice(void)" (?createVltDevice@SceGnmDriver@sce@@AEAA_NXZ)
2>SceGnmDriver.obj : : error LNK2019: unresolved external symbol "public: class sce::vlt::Rc<class sce::vlt::VltAdapter> __cdecl sce::vlt::VltInstance::enumAdapters(unsigned int)const " (?enumAdapters@VltInstance@vlt@sce@@QEBA?AV?$Rc@VVltAdapter@vlt@sce@@@23@I@Z) referenced in function "private: bool __cdecl sce::SceGnmDriver::createVltDevice(void)" (?createVltDevice@SceGnmDriver@sce@@AEAA_NXZ)
2>SceGnmDriver.obj : : error LNK2019: unresolved external symbol "public: class sce::vlt::Rc<class sce::vlt::VltDevice> __cdecl sce::vlt::VltAdapter::createDevice(class sce::vlt::Rc<class sce::vlt::VltInstance> const &)" (?createDevice@VltAdapter@vlt@sce@@QEAA?AV?$Rc@VVltDevice@vlt@sce@@@23@AEBV?$Rc@VVltInstance@vlt@sce@@@23@@Z) referenced in function "private: bool __cdecl sce::SceGnmDriver::createVltDevice(void)" (?createVltDevice@SceGnmDriver@sce@@AEAA_NXZ)
2>VltDevice.obj : : error LNK2019: unresolved external symbol "public: struct sce::vlt::VltAdapterQueueIndices __cdecl sce::vlt::VltAdapter::findQueueFamilies(void)const " (?findQueueFamilies@VltAdapter@vlt@sce@@QEBA?AUVltAdapterQueueIndices@23@XZ) referenced in function "public: __cdecl sce::vlt::VltDevice::VltDevice(class sce::vlt::Rc<class sce::vlt::VltInstance> const &,class sce::vlt::Rc<class sce::vlt::VltAdapter> const &,struct VkDevice_T *,struct sce::vlt::VltDeviceExtensions const &,struct sce::vlt::VltDeviceFeatures const &)" (??0VltDevice@vlt@sce@@QEAA@AEBV?$Rc@VVltInstance@vlt@sce@@@12@AEBV?$Rc@VVltAdapter@vlt@sce@@@12@PEAUVkDevice_T@@AEBUVltDeviceExtensions@12@AEBUVltDeviceFeatures@12@@Z)
2>VltDevice.obj : : error LNK2019: unresolved external symbol "public: bool __cdecl sce::vlt::VltAdapter::isUnifiedMemoryArchitecture(void)const " (?isUnifiedMemoryArchitecture@VltAdapter@vlt@sce@@QEBA_NXZ) referenced in function "public: bool __cdecl sce::vlt::VltDevice::isUnifiedMemoryArchitecture(void)const " (?isUnifiedMemoryArchitecture@VltDevice@vlt@sce@@QEBA_NXZ)
2>VltMemory.obj : : error LNK2019: unresolved external symbol "public: void __cdecl sce::vlt::VltAdapter::notifyHeapMemoryFree(unsigned int,unsigned __int64)" (?notifyHeapMemoryFree@VltAdapter@vlt@sce@@QEAAXI_K@Z) referenced in function "private: void __cdecl sce::vlt::VltMemoryAllocator::free(class sce::vlt::VltMemory const &)" (?free@VltMemoryAllocator@vlt@sce@@AEAAXAEBVVltMemory@23@@Z)
2>VltMemory.obj : : error LNK2019: unresolved external symbol "public: struct VkPhysicalDeviceMemoryProperties __cdecl sce::vlt::VltAdapter::memoryProperties(void)const " (?memoryProperties@VltAdapter@vlt@sce@@QEBA?AUVkPhysicalDeviceMemoryProperties@@XZ) referenced in function "public: __cdecl sce::vlt::VltMemoryAllocator::VltMemoryAllocator(class sce::vlt::VltDevice const *)" (??0VltMemoryAllocator@vlt@sce@@QEAA@PEBVVltDevice@12@@Z)
2>VltMemory.obj : : error LNK2019: unresolved external symbol "public: struct sce::vlt::VltAdapterMemoryInfo __cdecl sce::vlt::VltAdapter::getMemoryHeapInfo(void)const " (?getMemoryHeapInfo@VltAdapter@vlt@sce@@QEBA?AUVltAdapterMemoryInfo@23@XZ) referenced in function "public: class sce::vlt::VltMemory __cdecl sce::vlt::VltMemoryAllocator::alloc(struct VkMemoryRequirements const *,struct VkMemoryDedicatedRequirements const &,struct VkMemoryDedicatedAllocateInfo const &,unsigned int,class util::Flags<enum sce::vlt::VltMemoryFlag>)" (?alloc@VltMemoryAllocator@vlt@sce@@QEAA?AVVltMemory@23@PEBUVkMemoryRequirements@@AEBUVkMemoryDedicatedRequirements@@AEBUVkMemoryDedicatedAllocateInfo@@IV?$Flags@W4VltMemoryFlag@vlt@sce@@@util@@@Z)
2>VltMemory.obj : : error LNK2019: unresolved external symbol "public: void __cdecl sce::vlt::VltAdapter::notifyHeapMemoryAlloc(unsigned int,unsigned __int64)" (?notifyHeapMemoryAlloc@VltAdapter@vlt@sce@@QEAAXI_K@Z) referenced in function "private: struct sce::vlt::VltDeviceMemory __cdecl sce::vlt::VltMemoryAllocator::tryAllocDeviceMemory(struct sce::vlt::VltMemoryType *,unsigned int,unsigned __int64,class util::Flags<enum sce::vlt::VltMemoryFlag>,struct VkMemoryDedicatedAllocateInfo const *)" (?tryAllocDeviceMemory@VltMemoryAllocator@vlt@sce@@AEAA?AUVltDeviceMemory@23@PEAUVltMemoryType@23@I_KV?$Flags@W4VltMemoryFlag@vlt@sce@@@util@@PEBUVkMemoryDedicatedAllocateInfo@@@Z)
2>C:\Users\thx4ever\Desktop\GPCS4\x64\Release\GPCS4.exe : : error LNK1120: 9 unresolved externals
2>Done building project "GPCS4.vcxproj" -- FAILED.
Any idea whats going on?

Regards

**Comment by Inori** [comment]
Have you read the [Developer Guide](https://github.com/Inori/GPCS4/blob/master/Doc/DeveloperGuide.md)?
There are up-to-date build steps.

**Comment by Inori** [comment]
And it seems you are using MSVC's linker.  
You need to use lld-link instead.

**Comment by thx4ever** [comment]
OK now lld-link errors
clang-cl : warning : argument unused during compilation: '/showFilenames' [-Wunused-command-line-argument]
1>clang-cl : warning : argument unused during compilation: '/showFilenames' [-Wunused-command-line-argument]
1>lld-link : error : undefined symbol: public: __cdecl sce::vlt::VltInstance::VltInstance(void)
1>>>> referenced by Graphics\Sce\SceGnmDriver.cpp
1>>>>               x64\Release\SceGnmDriver.obj
1>
1>lld-link : error : undefined symbol: public: class sce::vlt::Rc<class sce::vlt::VltAdapter> __cdecl sce::vlt::VltInstance::enumAdapters(unsigned int) const
1>>>> referenced by Graphics\Sce\SceGnmDriver.cpp
1>>>>               x64\Release\SceGnmDriver.obj
1>
1>lld-link : error : undefined symbol: public: class sce::vlt::Rc<class sce::vlt::VltDevice> __cdecl sce::vlt::VltAdapter::createDevice(class sce::vlt::Rc<class sce::vlt::VltInstance> const &)
1>>>> referenced by Graphics\Sce\SceGnmDriver.cpp
1>>>>               x64\Release\SceGnmDriver.obj
1>
1>lld-link : error : undefined symbol: public: struct sce::vlt::VltAdapterQueueIndices __cdecl sce::vlt::VltAdapter::findQueueFamilies(void) const
1>>>> referenced by Graphics\Violet\VltDevice.cpp
1>>>>               x64\Release\VltDevice.obj
1>
1>lld-link : error : undefined symbol: public: bool __cdecl sce::vlt::VltAdapter::isUnifiedMemoryArchitecture(void) const
1>>>> referenced by Graphics\Violet\VltDevice.cpp
1>>>>               x64\Release\VltDevice.obj
1>
1>lld-link : error : undefined symbol: public: struct VkPhysicalDeviceMemoryProperties __cdecl sce::vlt::VltAdapter::memoryProperties(void) const
1>>>> referenced by Graphics\Violet\VltMemory.cpp
1>>>>               x64\Release\VltMemory.obj
1>
1>lld-link : error : undefined symbol: public: struct sce::vlt::VltAdapterMemoryInfo __cdecl sce::vlt::VltAdapter::getMemoryHeapInfo(void) const
1>>>> referenced by Graphics\Violet\VltMemory.cpp
1>>>>               x64\Release\VltMemory.obj
1>
1>lld-link : error : undefined symbol: public: void __cdecl sce::vlt::VltAdapter::notifyHeapMemoryAlloc(unsigned int, unsigned __int64)
1>>>> referenced by Graphics\Violet\VltMemory.cpp
1>>>>               x64\Release\VltMemory.obj
1>
1>lld-link : error : undefined symbol: public: void __cdecl sce::vlt::VltAdapter::notifyHeapMemoryFree(unsigned int, unsigned __int64)
1>>>> referenced by Graphics\Violet\VltMemory.cpp
1>>>>               x64\Release\VltMemory.obj
1>Done building project "GPCS4.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by thx4ever** [comment]
OK i managed to build it but only the debug version, release version have unresolved externals

**Comment by Inori** [comment]
Some source file are excluded from build unintentionally.
Now fixed.
You can have a try.

**Comment by thx4ever** [comment]
OK thanks
