### ISSUE TITLE
Problem compiling project from Visual Studio 2022

### ISSUE THREAD

**Issue by Roboticy3** [Inori/GPCS4#121]
Just installed VS22 to try and build this project and was scratching my head at the following errors all day:

Error: linking multiple files is not supported yet. Use -c to compile files individually.	GPCS4	glslc	1 (x3)
Error: MSB8066	Custom build for 'Graphics\Sce\Shaders\sce_present_frag.frag;Graphics\Sce\Shaders\sce_present_frag_blit.frag;Graphics\Sce\Shaders\sce_present_vert.vert' exited with code 1.	GPCS4	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	245	

The second error is from Visual Studio, not the GitHub project. What I assume is happening is the "Custom Build" for these files, which happen to be all the files in the ["Shaders" folder](https://github.com/Inori/GPCS4/tree/master/GPCS4/Graphics/Sce/Shaders) on the GitHub project, is trying to link them somehow. It's failing to link them because that feature is not in whatever version of glslc is being used.

I tried:
 - compiling the files manually through the Visual Studio Powershell
 - getting rid of the files and then rebuilding
 - building the project on VS19

Is there a version of Vulkan that supports linking? Has anybody else had this problem?

**Comment by Roboticy3** [comment]
[here's what the console says when I try to build the full solution or just the GPCS4 part of the project](https://user-images.githubusercontent.com/63760047/164952404-0bce9af4-f213-45fb-80d9-a5c8670c3e52.png)

**Comment by Inori** [comment]
Seems your glslc is  trying to `link` the compiled shader files.
I don't get it, `link` should only happen at program runtime.
`cd` to `Graphics\Sce\Shaders\` folder and run:
`glslc -mfmt=num -o test.txt .\sce_present_frag.frag`
and see what's the output?

BTW, my glslc version is
```
shaderc v2022.1 v2022.1
spirv-tools v2022.2-dev v2022.1-5-gb846f8f1
glslang 11.1.0-408-gc34bb3b6
```

**Comment by Roboticy3** [comment]
Your compile command is different from the one I used (`glslc -c sce_present_frag.frag`). I'll try your and check my Vulcan version when I can.

**Comment by Roboticy3** [comment]
After testing, the fix for this particular issue is to use Inori's version of Vulkan, 1.3.204.1, instead of the current stable version.

**Comment by Inori** [comment]
My vulkan sdk is also a stable version, it was the latest version the time I downloaded.
It seems there's some changes about glslc between the two.

**Comment by Roboticy3** [comment]
sry, I mean just the current version.

**Comment by Inori** [comment]
It shouldn't any problems building pthread4w, and its' build system is not cmake.
You have to install clang build tools for visual studio on the new machine.

**Comment by Roboticy3** [comment]
I must of messed something up there. I followed all the steps in the Development Guide just like with the other machine, but ill try again tomorrow or the day after.

**Comment by Roboticy3** [comment]
It looks like the issue with pthreads is in the directories its using. It's not able into import any basic c++ libs like stdio and stuff, while all the others work perfectly fine. I have all the clang tools and stuff but I don't know what's going on. I'll work on finding the directory to VS22's c++ Microsoft SDK that everything else is using.

**Comment by gandalfthewhite19890404** [comment]
For some reasons Appveyor fails at compiling at same place.
But if you're connect via rdp to compiling appveyor workstation and build project by yourself - it is gonna be compiled (read below).
But had to disable vcpkg usage in gpcs4 settings, it does not compiling if it set to on:
![image](https://user-images.githubusercontent.com/24764335/165298383-70cf2527-a17e-4897-8a5b-58f07bda5303.png)

**Comment by Roboticy3** [comment]
I don't have that menu in my GPCS4 properties, how do you have your project set up?

**Comment by Inori** [comment]
I just installed the latest vulkan sdk and vs2022 with the two clang component on a new computer,
and I can build the fresh cloned latest code following the build instructions without any problem.
I don't think there's build issues for the project.

**Comment by Roboticy3** [comment]
That's why I don't think I should open a new issue for my current difficulties, clearly it's an issue on my end. I can try again with the latest vulkan sdk and current build another day and I'll just keep trying to sort things out. Wish me luck!
