### ISSUE TITLE
Unhandled exception at 0x00007FF7891A4A56 in GPCS4.exe:

### ISSUE THREAD

**Issue by Brutal-sam** [Inori/GPCS4#133]
![gggfg](https://user-images.githubusercontent.com/94696121/172984724-88e28744-7ce4-49e6-b76e-32e93a03ef06.JPG)

Unhandled exception at 0x00007FF7891A4A56 in GPCS4.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

**Comment by Inori** [comment]
Well, that maybe because I didn't handle null `attr`.
Try to do an nullptr check before deference `attr`.

**Comment by Brutal-sam** [comment]
@Inori no idea how to do that, I'm not a dev but I do know how to follow instruction and I got everything built and ready except this error

**Comment by Inori** [comment]
Should be [fixed](7317379de8dbfaa68ab9e1a0575542bdca9f0cb1).

**Comment by Brutal-sam** [comment]
@Inori sorry for the many questions but I get this invalid token when building the 3dlibrary from a local folder, tinyBDR making trouble as always, in any version I download locally it's always tinyBDR error invalid token and "error.hpp is missing" when building gpcs4. one last question which branch should I check out to test the game "we are doomed"? I know not all branches are for game testing.
![Capture](https://user-images.githubusercontent.com/94696121/173242375-5d091c87-1cbe-4877-9887-1b8b869d1a84.JPG)

**Comment by Inori** [comment]
If you don't how the program works, there will be more and more problems.
Obviously, GPCS4 is not ready for end-users.
