### ISSUE TITLE
Failure to build 

### ISSUE THREAD

**Issue by ZeBZKIE** [Inori/GPCS4#134]
1>------ Build started: Project: Zycore, Configuration: Debug x64 ------
2>------ Build started: Project: glfw, Configuration: Debug x64 ------
3>------ Build started: Project: rtaudio, Configuration: Debug x64 ------
4>------ Build started: Project: TinyDBR, Configuration: Debug x64 ------
5>------ Build started: Project: winpthreads, Configuration: Debug x64 ------
6>------ Build started: Project: fmt, Configuration: Debug x64 ------
1>D:\visual studio 2017\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5): error MSB8020: The build tools for ClangCL (Platform Toolset = 'ClangCL') cannot be found. To build using the ClangCL build tools, please install ClangCL build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
1>Done building project "Zycore.vcxproj" -- FAILED.
7>------ Build started: Project: Zydis, Configuration: Debug x64 ------
7>D:\visual studio 2017\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5): error MSB8020: The build tools for ClangCL (Platform Toolset = 'ClangCL') cannot be found. To build using the ClangCL build tools, please install ClangCL build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
7>Done building project "Zydis.vcxproj" -- FAILED.
2>D:\visual studio 2017\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5): error MSB8020: The build tools for ClangCL (Platform Toolset = 'ClangCL') cannot be found. To build using the ClangCL build tools, please install ClangCL build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
2>Done building project "glfw.vcxproj" -- FAILED.
3>D:\visual studio 2017\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5): error MSB8020: The build tools for ClangCL (Platform Toolset = 'ClangCL') cannot be found. To build using the ClangCL build tools, please install ClangCL build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
3>Done building project "rtaudio.vcxproj" -- FAILED.
4>D:\visual studio 2017\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5): error MSB8020: The build tools for ClangCL (Platform Toolset = 'ClangCL') cannot be found. To build using the ClangCL build tools, please install ClangCL build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
4>Done building project "TinyDBR.vcxproj" -- FAILED.
5>D:\visual studio 2017\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5): error MSB8020: The build tools for ClangCL (Platform Toolset = 'ClangCL') cannot be found. To build using the ClangCL build tools, please install ClangCL build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
5>Done building project "winpthreads.vcxproj" -- FAILED.
6>D:\visual studio 2017\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5): error MSB8020: The build tools for ClangCL (Platform Toolset = 'ClangCL') cannot be found. To build using the ClangCL build tools, please install ClangCL build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
6>Done building project "fmt.vcxproj" -- FAILED.
========== Build: 0 succeeded, 7 failed, 0 up-to-date, 0 skipped ==========

Help?

**Comment by ZeBZKIE** [comment]
Both the 3rd party file and the gpcs4 file fail to build entirely

**Comment by Inori** [comment]
You didn't install clang build component from vs installer.
Follow the instruction in [DeveloperGuide](https://github.com/Inori/GPCS4/blob/master/Doc/DeveloperGuide.md)
