### ISSUE TITLE
hi im trying to use gpcs4 but its saying gpcs4.exe throwed a debugbreakpoint inori please help me

### ISSUE THREAD

**Issue by emustuff** [Inori/GPCS4#135]
Basically, the Issues page only accept program bug report.
For feature request, suggestions and other questions, go to Discussions page: https://github.com/Inori/GPCS4/discussions

**Comment by Inori** [comment]
Obviously GPCS4 is not ready for end users as of now.
If you are not a developer, it's better to wait for release.

**Comment by emustuff** [comment]
hello inori thanks for the reply can you please tell can we play god of war 4 whithout crashing

**Comment by Inori** [comment]
yes, you can.
