### ISSUE TITLE
Bugs from PVS-Studio check

### ISSUE THREAD

**Issue by KurenevAlexandr** [Inori/GPCS4#137]
Hello,
we checked GPCS4 with static analyzer PVS-Studio and found some bugs. Here is an [article](https://pvs-studio.com/en/blog/posts/cpp/0955/) about it. May be you will fix some problems.

**Comment by Inori** [comment]
Thanks for the excellent tools and time for writing the blog.
I've [fixed ](https://github.com/Inori/GPCS4/commit/9d2f0907e9ca4d078ddea0a647bc53b93329c444) almost all the bugs pointed out in that blog.

Some of the code which looks very ugly is copy-pasted from disassemble tools and need more time to refactor so currently I did fix them.

Never though I could write so many foolish code. Thanks again.

Btw, I tried PVS-Studio myself with command like:
```
.\PVS-Studio_Cmd.exe -t C:\Dev\GPCS4\GPCS4\GPCS4.vcxproj -p "x64" -c "Release"
```
but I got:
```
No project files were found for analysis under the specified platform/configuration.
```
Do you know why?
