### ISSUE TITLE
basic-sample demo crashes

### ISSUE THREAD

**Issue by Inori** [Inori/GPCS4#14]
Currently basic-sample demo will crash on some functions.
If we can run it in an infinite loop without crash, just lacking of graphics output, that would be good for future module development.

**Comment by mailwl** [comment]
as  i can see, first stop at unimplemented `sceKernelPollEventFlag`, it may be just stubbed to return 0, but i don't understand, how to get hex value for function
`{ 0x??????????????????, "sceKernelPollEventFlag", (void*)sceKernelPollEventFlag },`
it would be easy, if first parameters in structure be a string, like
`{ "9lvj5DjHZiA", "sceKernelPollEventFlag", (void*)sceKernelPollEventFlag },`

**Comment by VelocityRa** [comment]
The value is the NID for the function, it's like an ID code for every exported function. The biggest database of them is this (pick a version) https://github.com/idc/ps4libdoc

Not all of them are known, they are determined by a hash function that contains keys unknown, so the ones we do know have been determined from symbols, the SDK or hash bruteforce.

It can't be a string, PS4 NIDs are not necessarily printable ASCII characters.

**Comment by Inori** [comment]
@mailwl @VelocityRa 
The first field of the structure is NID, which is a hash value of the function name string.
The NID of a function can be calculated by an algorithm, and here it is:
https://github.com/Inori/GPCS4/blob/master/Tools/NidFromFuncName.py
Of course we can't do the reverse, from hash to function name.
The NID can be represented as a string or a `uint64_t` value, there's no difference between them, the string version can be decoded using a function like this:
https://github.com/Inori/GPCS4/blob/master/GPCS4/Loader/ELFMapper.cpp#L764
I define it as a `uint64_t` just for speed.
A complete NID string also contains module name and library name code, and formed like `ac#ed#7AIGydK+E48`, this also can be decoded using the [same function](https://github.com/Inori/GPCS4/blob/master/GPCS4/Loader/ELFMapper.cpp#L824)
The decoded integer value can be mapped to specific modules and libraries, just I don't remember the relationship.

**Comment by VelocityRa** [comment]
Yeah, my bad, I completely forgot about their base64 representation. I always see the `uint64_t` one.

About the `aerolib.csv`, yes Socratic's db probably has more NIDs since he has done a bunch of hash cracking (along with Chendo, etc), but it's just NID -> name, no other info as in ps4libdoc.
So it's useful for some things, not very useful for others.
