### ISSUE TITLE
"Conflicting types for 'atomic_thread_fence' " 

### ISSUE THREAD

**Issue by Arthurfogo7** [Inori/GPCS4#142]
![image](https://user-images.githubusercontent.com/85951083/184419806-caf96429-9deb-411a-bd81-cb0553ec23cc.png)

I'm trying to compile TinyDBR, but this error always occur. I'm using Visual Studio 2022 and Windows 10.

**Comment by Inori** [comment]
Comment out those two lines in Clang header
