### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by KT7000** [Inori/GPCS4#144]
When I try to build on Visual Studio 2022, I get this error message

<img width="1280" alt="01" src="https://user-images.githubusercontent.com/90338912/197283863-3b16f5a9-93b0-4f25-a01a-4fb306d2f74b.png">

How do I fix this?

**Comment by Inori** [comment]
Seems you haven't installed Vulkan SDK properly, try:
1. close your visual studio.
2. uninstall your vulkan sdk
3. download latest lunaG vulkan sdk and reinstall
4. open your visual studio again.

**Comment by KT7000** [comment]
I downloaded and installed the latest version of vulkan sdk, but when I opened visual studio and tried to build gpcs4 I got this error message

<img width="1280" alt="2022-11-04 11_57_35-Greenshot" src="https://user-images.githubusercontent.com/90338912/200022319-2f545e36-c55a-4f5c-865f-c2b212f7e883.png">

**Comment by KT7000** [comment]
> Seems you haven't installed Vulkan SDK properly, try:
> 
> 1. close your visual studio.
> 2. uninstall your vulkan sdk
> 3. download latest lunaG vulkan sdk and reinstall
> 4. open your visual studio again.

I downloaded and installed the latest version of vulkan sdk, but when I opened visual studio and tried to build gpcs4 again, I got this error message

<img width="1280" alt="2022-11-04 11_57_35-Greenshot" src="https://user-images.githubusercontent.com/90338912/200022319-2f545e36-c55a-4f5c-865f-c2b212f7e883.png">

**Comment by Masamune3210** [comment]
Given the fact that its failing to open the header files, I'm going to assume there is still some issue with either your envvars, your visual studio install, or your vulkan SDK install

**Comment by KT7000** [comment]
> Given the fact that its failing to open the header files, I'm going to assume there is still some issue with either your envvars, your visual studio install, or your vulkan SDK install

What do I do?

**Comment by Inori** [comment]
Make sure you installed Vulkan SDK properly.
