### ISSUE TITLE
use of undeclared identifier 'memory_order_relaxed'

### ISSUE THREAD

**Issue by paulomanrique** [Inori/GPCS4#146]
When trying to compile the TinyDBR, I get the following error:

use of undeclared identifier 'memory_order_relaxed', tinydbr.cpp, line 237

The part of the code where the error happens:

```c
#ifdef __clang__
	__c11_atomic_store(ptr, value, memory_order_relaxed);
#else
	// x86 machine aligned memory store should be atomic natively.
	*ptr = value;
#endif
```

I'm using the latest vstudio enterprise with all the latest libraries.

**Comment by Inori** [comment]
Fixed
