### ISSUE TITLE
load game provided modules first, then system's

### ISSUE THREAD

**Issue by Inori** [Inori/GPCS4#17]
for me, as every ps4 game includes own version of libc, better way to load provided version of libc.prx

_Originally posted by @mailwl in https://github.com/Inori/GPCS4/pull/16#issuecomment-557895696_

**Comment by Inori** [comment]
Yes, you're right, we should load modules in game's `sce_module` folder first then fall to system's.
It's just we only have a few programs being worked on currently, so that's not a big problem and I delay that work.

**Comment by VelocityRa** [comment]
Added to Trello with low priority tag.
