### ISSUE TITLE
emulate PS4 filesystem

### ISSUE THREAD

**Issue by mailwl** [Inori/GPCS4#23]
I suggest do not use path to eboot.bin as cmd line parameters, and use this structure:

> GPCS4.exe
> app0/
> -eboot.bin
> -sce_module/
> -- libc.prx libSceFios2.prx, and other from game
> dev/
> -- dce, gc, and other which wants system modules
> system/
> -- common/
> --- lib/
> ---- *.sprx - from PS4 dump

with this name system, it's easier to just replace app0 folder from game dumps for tests

**Comment by VelocityRa** [comment]
So we'll have to copy `app0/` around every time we want to run a different game? 
I don't get it.

Anyway, we do need better VFS emulation, it's basically non-existent atm. We just pass everything to host.

Join our Discord if you want, most development discussion happens there.

**Comment by mailwl** [comment]
for development time, yes, i think it's easier (at least, for myself), because games always read own files from /app0/. for production sure need a list of installed apps (i don't know, if it's possible to run a game right from .pkg).

**Comment by VelocityRa** [comment]
Right.

Well, it's possible to run a game from .pkg (via a VFS system) but not very easy, needs work.

What's easier I think, is creating a directory tree that resembles PS4 tree, install games there and intercept requests to `app0/` etc and direct them to there. Without dealing with `.pkg`s yet.

**Comment by Inori** [comment]
Currently I just map the directory which `GPCS4.exe` locate as `app0`, and redirect every `app0` access to this directory. see [here](https://github.com/Inori/GPCS4/blob/master/GPCS4/Platform/UtilPath.cpp#L37).

But let's just ignore these trifles for now and focus on [more important things](https://github.com/Inori/GPCS4/projects/1) and make real progress.

**Comment by VelocityRa** [comment]
Huh? Emulating app0 is pretty important, that's where all game files are isn't it?
I don't see how using `GPCS4.exe`'s path makes any sense, it sounds even worse than what the OP suggested.

Also, I thought we agreed we would use Trello and not GitHub Projects.
I don't care either way but decide on something and let's delete the other, else there is no point.

**Comment by Inori** [comment]
Emulating app0 is important, yes, but not for now, current implementation just ***works***, better than nothing. And I think what we should really focus on is the `nothing` parts.

But if anyone just like to do the work of emulating filename system, implement a simple one is ok, I vote for @mailwl 's design. Just make pull request.

About Trello, like I said, I use git project to maintain a small todo list just for conciseness and publicly review. It's not conflict with with Trello.

**Comment by VelocityRa** [comment]
The Trello is public too, we can just link it in the README.
If you want a TODO list just for yourself you can make a new list, like `To Do - Asuka`.

Ok about `app0/`, we'll deal with it when needed.

**Comment by Inori** [comment]
Ok, I'm going to migrate the todo list to trello.
