### ISSUE TITLE
Inori May you add me righs to add comments for project

### ISSUE THREAD

**Issue by mailwl** [Inori/GPCS4#27]

**Comment by mailwl** [comment]
on diskord

**Comment by VelocityRa** [comment]
...Why would you make an issue for this? This is not what the Issue Tracker is for.

Ask whatever you want on Discord. If you want someone's attention ping them with @.

**Comment by Inori** [comment]
It's ok, we don't need to be so serious.
What do you mean by saying `add comments for project` ?

**Comment by VelocityRa** [comment]
I just didn't see the point. He's already on Discord.
We don't know what he meant and it's much faster to communicate there.

**Comment by mailwl** [comment]
gpcs4-github not allow to post, maybe you allow me? but for now i don't really need this

**Comment by VelocityRa** [comment]
I have no idea:
1) why you didn't notice that the only user that ever posted in there is a bot
2) why you didn't infer from that, that _noone_ has permission to post there, not just you
2) why you would want to post anything there
3) why would you ask for this _here_
4) why would you ask for this at all

So many questions.

Anyway, hopefully your questions were answered.

**Comment by mailwl** [comment]
yes, i undersand. eventualy visit this channel

**Comment by Inori** [comment]
It's just an information channel using to remind people something happend on Github, no one need to post messages on that channel including myself.
