### ISSUE TITLE
"mov     rax, fs:0x0" - how to work with it on windows?

### ISSUE THREAD

**Issue by mailwl** [Inori/GPCS4#4]
I am try to work with "The Last of Us", and stuck at
```
CODE:0000000000AAEBB0 sub_AAEBB0      proc near               ; CODE XREF: sub_AA1D40+24↑p
CODE:0000000000AAEBB0                                         ; sub_AA1D40+37↑p ...
CODE:0000000000AAEBB0                 push    rax
CODE:0000000000AAEBB1                 mov     rax, fs:0x0
CODE:0000000000AAEBBA                 add     rax, cs:15D27D8h
CODE:0000000000AAEBC1                 mov     rdi, [rax]
CODE:0000000000AAEBC4                 pop     rax
CODE:0000000000AAEBC5                 jmp     sub_AA6BF0
CODE:0000000000AAEBC5 sub_AAEBB0      endp
```
crash at 0xAAEBB1 - there is any way to fix it?
(i trying not exactly your code, but i think, the problem is common)

**Comment by Inori** [comment]
What code are you trying？ You can join our discord and we can discuss there.

**Comment by VelocityRa** [comment]
See ["Executing *BSD ELFs on Windows"](http://ghettohaxxx-blog.azurewebsites.net/executing-bsd-elfs-in-windows/).
The exception handler method works fine.
It solves `fs` usage, but you'll still need a solution for other TLS methods (particularly `__tls_get_addr`) later on.
Please join the Discord if you want to discuss this more as @Inori said, GitHub isn't the place to do so.
