### ISSUE TITLE
Release build crashes.

### ISSUE THREAD

**Issue by Inori** [Inori/GPCS4#42]
![unknown](https://user-images.githubusercontent.com/6732524/73729834-b82baa00-4770-11ea-8b30-db5db6703f85.png)
The release build will crash on `vkUpdateDescriptorSets`

**Comment by Inori** [comment]
Fixed

**Comment by Brutal-sam** [comment]
@Inori where's the fix? I'm having a similar issue with 0.2.1

**Comment by Inori** [comment]
I didn't try release build for that release to be honest.
Maybe you need to use debug build.
But at the time of closing this issue, I changed all the 3rd party libraries to be compiled with clang (previously 3rd party libraries are compiled with msvc.), the the release build works.

**Comment by Inori** [comment]
Just tried release build, it works just like debug build.
Maybe you should rebuild 3rd party libraries.
