### ISSUE TITLE
Emulator crashing with TLSManagerWin exception

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Inori/GPCS4#49]
Tried with we_are_doomed branch (testers already boots that game so I tried too, some commits before - because of logging to text file) - gpcs4 just closing, only thing i have got - white screen for second.
Latest logged thing is:
![image](https://user-images.githubusercontent.com/24764335/73970205-2bcae400-4936-11ea-9383-23f6a932171f.png)
Could it be due old (if it possible at all) TLSManagerWin - I'm using Windows 10 17633.979?
I attached log file but its shrinked for some reason, have to get by DebugView
Hardware - Intel i3-6100, RTX 2060.

[GPCS4.zip](https://github.com/Inori/GPCS4/files/4167313/GPCS4.zip)

**Comment by Inori** [comment]
Thanks for your test.
But since GPCS4 is still at a very early stage and unstable, we are not going to solve individual user problems at the moment.
Please read the faq channel in our discord server.
