### ISSUE TITLE
Some games asserts into __fastfail(FAST_FAIL_INVALID_ARG)

### ISSUE THREAD

**Issue by JohnGodgames** [Inori/GPCS4#51]
I have no more info

![issue 1](https://user-images.githubusercontent.com/11453507/73988969-92ef9500-4944-11ea-84df-8729e6bf966b.JPG)
![issue 2](https://user-images.githubusercontent.com/11453507/73988978-97b44900-4944-11ea-95fa-1c6d91d2a5cd.JPG)

**Comment by Inori** [comment]
Thanks for your test.
But since GPCS4 is still at a very early stage, games other than We are doomed will not be supported.
And we won't solve individual user problems currently.
Please read the faq channel in our discord server.
