### ISSUE TITLE
Why this exist if orbital created a long time ago?

### ISSUE THREAD

**Issue by megapro17** [Inori/GPCS4#62]
Is this completely different idea or what? Seems yours is developed much faster, can even start one game
https://github.com/AlexAltea/orbital

**Comment by rhyacinth** [comment]
Orbital is a very different project from this one, Orbital serves to run the entire PS4 firmware through virtualization where as this is intended for the purpose of running PS4 games. One is far larger in scope than the other.

**Comment by Inori** [comment]
This is not an issue, such questions can be discussed in our discord server.
