### ISSUE TITLE
can add basic_quad.elf?

### ISSUE THREAD

**Issue by oscarbg** [Inori/GPCS4#65]
just for simple testing on Wine..

**Comment by q4a** [comment]
This project need to add FAQ, but I already asked this in Discord:
- Does builded samples from sdk are "piracy"?
- Yes, untill it is not compiled with open sourse PS4 SDK.

Currently there is no good open sourse PS4 SDK.

PS Wine - so, you are going to test in Linux. Looks like better port it in Linux in early stage.

**Comment by Inori** [comment]
There is already faq in discord.
