### ISSUE TITLE
PlayStation 4 cd, will it be able to run it?

### ISSUE THREAD

**Issue by ghost** [Inori/GPCS4#84]
PlayStation 4 cd, will it be able to run it?

**Comment by ilan0098** [comment]
I guess not , since the emulator isn't ready yet to RUN games at all , if it would , I guess it could run even downloaded games,  but it's not , so I guess not , anyways , wait for another answers from expreted people,  i'm sure they will give yoy a better answer

**Comment by gs-soda** [comment]
no

**Comment by Inori** [comment]
Not possible.
