### ISSUE TITLE
nah

### ISSUE THREAD

**Issue by MysticCodes** [Inori/GPCS4#88]
gg

**Comment by fourmagit** [comment]
cool! are you able to grab footage or screenshots of the emu in action?

**Comment by Azerrs** [comment]
> cool! are you able to grab footage or screenshots of the emu in action?

Currently in development but we are trying to optimize the emulator and you will be able to play it we have a lot of bugs but its still more stable than GPCS4, thanks for the interest in my emulator you will not regret it

**Comment by agentwolf88** [comment]
I dont think so XD

**Comment by gs-soda** [comment]
im pretty sure he asked for screenshots right? i mean you can always just start days gone (because it runs perfectly) and make a screenshot ayy?

**Comment by VelocityRa** [comment]
@Inori Please lock & close.

**Comment by Loganbogan9** [comment]
> 
> 
> > cool! are you able to grab footage or screenshots of the emu in action?
> 
> Currently in development but we are trying to optimize the emulator and you will be able to play it we have a lot of bugs but its still more stable than GPCS4, thanks for the interest in my emulator you will not regret it

So it's fake is what you're saying.

**Comment by isinyaaa** [comment]
it's a scam, he's literally trying to sell some weird code, idk even if it exists, but i guess it's best to be careful.

**Comment by Azerrs** [comment]
> it's a scam, he's literally trying to sell some weird code, idk even if it exists, but i guess it's best to be careful.

okay man keep saying that its not a scam

**Comment by Masamune3210** [comment]
It is a scam until proven otherwise, that's how burden of proof works. Most people making a emu wouldn't randomly post in the issues of another emu like this

**Comment by Azerrs** [comment]
> It is a scam until proven otherwise, that's how burden of proof works. Most people making a emu wouldn't randomly post in the issues of another emu like this

so tech dunk already knows its not fake i showed him proof

**Comment by Masamune3210** [comment]
Cool, you have supposedly shown a random youtuber. Is that supposed to change something? Either post the source so people know what's going on or nobody is going to believe you. Even if your supposed emulator is real, no way in heck anyone should run it without knowing exactly what it's doing

**Comment by liuziangexit** [comment]
I proved P=NP, but i won't show you how it's been proven, but this is totally true, its not a scam, believe me

**Comment by Graubek** [comment]
I hope that's not scam and we will get a good emulator.

**Comment by Masamune3210** [comment]
I still doubt this but whatever, you do you. Regardless this is not the place for this at all and needs to either be locked or closed, There are subreddits and forums for stuff like this

**Comment by Inori** [comment]
I didn't continue developing this project for a pretty long time and sorry for that, one of the reaseons is that I found it's pretty hard to find an acceptable and efficient way to monitor memory access for the game process, and we have to do this to virtualize GPU memory.
I'd like to know how do you solve this problem?

**Comment by VelocityRa** [comment]
@Inori
Was the Windows [64KB page granularity](https://devblogs.microsoft.com/oldnewthing/20031008-00/?p=42223) an issue? Because there **is** a solution to get around it and get 4KB granularity with a relatively recent windows API.

Please reach out to me on Discord or Twitter for details, I don't want to discuss this in this trash issue.

**Comment by liuziangexit** [comment]
> @Inori
> Was the Windows [64KB page granularity](https://devblogs.microsoft.com/oldnewthing/20031008-00/?p=42223) an issue? Because there **is** a solution to get around it and get 4KB granularity with a relatively recent windows API.
> 
> Please reach out to me on Discord or Twitter for details, I don't want to discuss this in this trash Issue.

Oh! Its written by Raymond!
