### ISSUE TITLE
Has this project been dropped?

### ISSUE THREAD

**Issue by isinyaaa** [Inori/GPCS4#89]
By the looks of it and status on https://emulation.gametechwiki.com/index.php/PlayStation_4_emulators, it DOES look like a ghost repo, unfortunately.
I want to contribute, but am not willing to take hold of this on my own...

**Comment by fourmagit** [comment]
Not entirely - the community is plenty active, and there are contributions every once in a while

**Comment by isinyaaa** [comment]
> Not entirely - the community is plenty active, and there are contributions every once in a while

should we fork this?

**Comment by MystifyCodes** [comment]
> > Not entirely - the community is plenty active, and there are contributions every once in a while
> 
> should we fork this?

why not
