### ISSUE TITLE
I'm making gpcs4 great again!

### ISSUE THREAD

**Issue by MystifyCodes** [Inori/GPCS4#92]
I'm making gpcs4 great again go to my profile and click on the making gpcs4 running other games for updates!

**Comment by Masamune3210** [comment]
please go shill somewhere else, this is not the place for it

**Comment by MystifyCodes** [comment]
> please go shill somewhere else, this is not the place for it

even the gpcs4 supporter are interested go take ur shit somewhere else lol hahahaha

**Comment by Masamune3210** [comment]
Are you broken? Or do you not realize that the only person on this issue is me and you. The issue reports are for issues with the project, not for you to vampire whatever support this project might have over to your fork just because you want to scam people or whatever.

**Comment by MystifyCodes** [comment]
> Are you broken? Or do you not realize that the only person on this issue is me and you. The issue reports are for issues with the project, not for you to vampire whatever support this project might have over to your fork just because you want to scam people or whatever.

i got 9 people expecting my work its called discord lol
