### ISSUE TITLE
Probably a stupid question about how active this is + Discord

### ISSUE THREAD

**Issue by UltimateEmboar** [Inori/GPCS4#93]
Is this still actively being worked on? From what I've seen there hasn't been a pull since April and it says it was last updated in 2019 so I guess I'm curious, Also if there's a Discord where fans or random people can just join and look in to view progress from time to time I'd love to have a link (I don't know if there's a way to flair this a certain way so apologies in advance)

**Comment by DimetryBadcoder** [comment]
Official Discord server is full of spammers talking about "free Nitro". 
I think this project is dead

**Comment by Masamune3210** [comment]
Not dead, just not super public facing

**Comment by Lamzas1234** [comment]
Hopefully they add some moderators to clean the scams.
