### ISSUE TITLE
can it run ps2 emulated games of the ps Store ?

### ISSUE THREAD

**Issue by seb16120** [Inori/GPCS4#94]
like this one (Rogue galaxy) : https://store.playstation.com/fr-fr/product/EP9000-CUSA02271_00-SCES545520000001/

**Comment by Masamune3210** [comment]
Did you just spam this onto every ps4 emu project you could find?

**Comment by seb16120** [comment]
Only 2.
Cause the 2 others i already understood it cannot.

Le mar. 17 août 2021 à 00:52, Masamune3210 ***@***.***> a
écrit :

**Comment by Inori** [comment]
Not on the plan.
