### ISSUE TITLE
请到我们呆萌公司报名！需要你这样的人才，每个人3100美元一个月！(重大进展必奖500＄+)来吧朋友！到我们呆萌贴吧。GO

### ISSUE THREAD

**Issue by xiaoxiaonaonao** [Inori/GPCS4#96]
请到我们呆萌公司报名！需要你这样的人才，每个人3100美元一个月！(重大进展必奖500＄+)来吧朋友！到我们呆萌贴吧。GO

**Comment by Masamune3210** [comment]
Please do not solicit on random peoples projects. Especially in a foreign language without permission

请不要随意在别人的项目上征集。特别是在未经许可的情况下用外语进行宣传

**Comment by xiaoxiaonaonao** [comment]
😌
